/*
* generated by Xtext
*/
package fr.imta.tp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.imta.tp.services.Sql4csvGrammarAccess;

public class Sql4csvParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Sql4csvGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.imta.tp.parser.antlr.internal.InternalSql4csvParser createParser(XtextTokenStream stream) {
		return new fr.imta.tp.parser.antlr.internal.InternalSql4csvParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SQL4CSV";
	}
	
	public Sql4csvGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Sql4csvGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
