/*
* generated by Xtext
*/
package fr.imta.tp2.calendarDSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CalendarDSLStandaloneSetup extends CalendarDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new CalendarDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

