/*
 * generated by Xtext
 */
package fr.imta.tp2.calendarDSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CalendarDSLRuntimeModule extends fr.imta.tp2.calendarDSL.AbstractCalendarDSLRuntimeModule {

}
