/*
 * generated by Xtext
 */
package fr.imta.tp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Sql4csvRuntimeModule extends fr.imta.tp.AbstractSql4csvRuntimeModule {

}
