/*
* generated by Xtext
*/
package fr.imta.tp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Sql4csvStandaloneSetup extends Sql4csvStandaloneSetupGenerated{

	public static void doSetup() {
		new Sql4csvStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

