/*
 * generated by Xtext
 */
package fr.imta.tp2.tutorial;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyTutoRuntimeModule extends fr.imta.tp2.tutorial.AbstractMyTutoRuntimeModule {

}
