/*
* generated by Xtext
*/
package fr.imta.tp2.tutorial;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyTutoStandaloneSetup extends MyTutoStandaloneSetupGenerated{

	public static void doSetup() {
		new MyTutoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

