/*
 * generated by Xtext
 */
package fr.imta.tp2.calendarDSL.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.imta.tp2.calendarDSL.ui.internal.CalendarDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CalendarDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CalendarDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CalendarDSLActivator.getInstance().getInjector(CalendarDSLActivator.FR_IMTA_TP2_CALENDARDSL_CALENDARDSL);
	}
	
}
