/*
 * generated by Xtext
 */
package fr.imta.tp2.statDSL.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.imta.tp2.statDSL.ui.internal.StatDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StatDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StatDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StatDSLActivator.getInstance().getInjector(StatDSLActivator.FR_IMTA_TP2_STATDSL_STATDSL);
	}
	
}
