/**
 * generated by Xtext
 */
package fr.imta.tp2.statDSL.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class StatDSLScopeProvider extends AbstractDeclarativeScopeProvider {
}
