/*
* generated by Xtext
*/
package fr.imta.tp2.calendarDSL;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CalendarDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imta.tp2.calendarDSL.ui.internal.CalendarDSLActivator.getInstance().getInjector("fr.imta.tp2.calendarDSL.CalendarDSL");
	}
	
}
