/*
 * generated by Xtext
 */
package fr.imta.tp2.calendarDSL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CalendarDSLUiModule extends fr.imta.tp2.calendarDSL.ui.AbstractCalendarDSLUiModule {
	public CalendarDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
