/*
 * generated by Xtext
 */
package fr.imta.tp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CalcDSLRuntimeModule extends fr.imta.tp.AbstractCalcDSLRuntimeModule {

}
