/*
* generated by Xtext
*/
package fr.imta.tp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CalcDSLStandaloneSetup extends CalcDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new CalcDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

