/*
 * generated by Xtext
 */
package fr.imta.tp2.calendarDSL.ui.contentassist

import fr.imta.tp2.calendarDSL.ui.contentassist.AbstractCalendarDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CalendarDSLProposalProvider extends AbstractCalendarDSLProposalProvider {
}
