/*
* generated by Xtext
*/
package fr.imta.tp2.tutorial.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyTutoAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/imta/tp2/tutorial/parser/antlr/internal/InternalMyTuto.tokens");
	}
}
