/*
* generated by Xtext
*/
package fr.imta.tp2.tutorial.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.imta.tp2.tutorial.services.MyTutoGrammarAccess;

public class MyTutoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MyTutoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.imta.tp2.tutorial.parser.antlr.internal.InternalMyTutoParser createParser(XtextTokenStream stream) {
		return new fr.imta.tp2.tutorial.parser.antlr.internal.InternalMyTutoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MyTuto";
	}
	
	public MyTutoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyTutoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
