/*
* generated by Xtext
*/
package fr.imta.tp2.tutorial;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyTutoUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imta.tp2.tutorial.ui.internal.MyTutoActivator.getInstance().getInjector("fr.imta.tp2.tutorial.MyTuto");
	}
	
}
