/**
 * generated by Xtext
 */
package fr.imta.tp2.tutorial.validation;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyTutoValidator /* implements AbstractMyTutoValidator  */{
}
