/*
 * generated by Xtext
 */
package fr.imta.tp.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.imta.tp.ui.internal.CalcDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CalcDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CalcDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CalcDSLActivator.getInstance().getInjector(CalcDSLActivator.FR_IMTA_TP_CALCDSL);
	}
	
}
