/*
 * generated by Xtext
 */
package fr.imta.tp.ui.contentassist

import fr.imta.tp.ui.contentassist.AbstractCalcDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CalcDSLProposalProvider extends AbstractCalcDSLProposalProvider {
}
