/*
 * generated by Xtext
 */
package fr.imta.tp.ui.contentassist

import fr.imta.tp.ui.contentassist.AbstractSql4csvProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class Sql4csvProposalProvider extends AbstractSql4csvProposalProvider {
}
