/*
* generated by Xtext
*/
package fr.imta.tp;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CalcDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imta.tp.ui.internal.CalcDSLActivator.getInstance().getInjector("fr.imta.tp.CalcDSL");
	}
	
}
