/*
 * generated by Xtext
 */
package fr.imta.tp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Sql4csvUiModule extends fr.imta.tp.ui.AbstractSql4csvUiModule {
	public Sql4csvUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
