/**
 * generated by Xtext
 */
package fr.imta.tp.validation;

import fr.imta.tp.validation.AbstractSql4csvValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class Sql4csvValidator extends AbstractSql4csvValidator {
}
