/*
 * generated by Xtext
 */
package fr.imta.tp2.statDSL.ui.contentassist

import fr.imta.tp2.statDSL.ui.contentassist.AbstractStatDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class StatDSLProposalProvider extends AbstractStatDSLProposalProvider {
}
