/*
* generated by Xtext
*/
package fr.imta.tp2.statDSL.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.imta.tp2.statDSL.services.StatDSLGrammarAccess;

public class StatDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StatDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.imta.tp2.statDSL.parser.antlr.internal.InternalStatDSLParser createParser(XtextTokenStream stream) {
		return new fr.imta.tp2.statDSL.parser.antlr.internal.InternalStatDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StatDSL";
	}
	
	public StatDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StatDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
