/*
* generated by Xtext
*/
package fr.imta.tp2.statDSL.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StatDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/imta/tp2/statDSL/parser/antlr/internal/InternalStatDSL.tokens");
	}
}
