/*
* generated by Xtext
*/
package fr.imta.tp2.statDSL;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StatDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imta.tp2.statDSL.ui.internal.StatDSLActivator.getInstance().getInjector("fr.imta.tp2.statDSL.StatDSL");
	}
	
}
