/*
* generated by Xtext
*/
package fr.imta.tp2.statDSL.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.imta.tp2.statDSL.services.StatDSLGrammarAccess;

public class StatDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private StatDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.imta.tp2.statDSL.ui.contentassist.antlr.internal.InternalStatDSLParser createParser() {
		fr.imta.tp2.statDSL.ui.contentassist.antlr.internal.InternalStatDSLParser result = new fr.imta.tp2.statDSL.ui.contentassist.antlr.internal.InternalStatDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getKeywordAccess().getAlternatives(), "rule__Keyword__Alternatives");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getEffAccess().getGroup(), "rule__Eff__Group__0");
					put(grammarAccess.getEffAccess().getGroup_2(), "rule__Eff__Group_2__0");
					put(grammarAccess.getModAccess().getGroup(), "rule__Mod__Group__0");
					put(grammarAccess.getModAccess().getGroup_2(), "rule__Mod__Group_2__0");
					put(grammarAccess.getStatDSLAccess().getProgramAssignment(), "rule__StatDSL__ProgramAssignment");
					put(grammarAccess.getProgramAccess().getNameAssignment_1(), "rule__Program__NameAssignment_1");
					put(grammarAccess.getInstructionsAccess().getUnorderedGroup(), "rule__Instructions__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.imta.tp2.statDSL.ui.contentassist.antlr.internal.InternalStatDSLParser typedParser = (fr.imta.tp2.statDSL.ui.contentassist.antlr.internal.InternalStatDSLParser) parser;
			typedParser.entryRuleStatDSL();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public StatDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StatDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
