/*
 * generated by Xtext
 */
package fr.imta.tp2.statDSL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatDSLUiModule extends fr.imta.tp2.statDSL.ui.AbstractStatDSLUiModule {
	public StatDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
