/**
 * generated by Xtext
 */
package fr.imta.tp2.statDSL.validation;

import fr.imta.tp2.statDSL.validation.AbstractStatDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class StatDSLValidator extends AbstractStatDSLValidator {
}
