/*
 * generated by Xtext
 */
package fr.imta.tp2.tutorial.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyTutoUiModule extends fr.imta.tp2.tutorial.ui.AbstractMyTutoUiModule {
	public MyTutoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
