/*
* generated by Xtext
*/
package fr.imta.tp;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Sql4csvUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imta.tp.ui.internal.Sql4csvActivator.getInstance().getInjector("fr.imta.tp.Sql4csv");
	}
	
}
