/*
 * generated by Xtext
 */
package fr.imta.tp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CalcDSLUiModule extends fr.imta.tp.ui.AbstractCalcDSLUiModule {
	public CalcDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
