/*
 * generated by Xtext
 */
package fr.imta.tp2.statDSL;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatDSLRuntimeModule extends fr.imta.tp2.statDSL.AbstractStatDSLRuntimeModule {

}
