/*
* generated by Xtext
*/
package fr.imta.tp2.statDSL;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class StatDSLStandaloneSetup extends StatDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new StatDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

