/**
 * generated by Xtext
 */
package fr.imta.tp.validation;

import fr.imta.tp.validation.AbstractCalcDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CalcDSLValidator extends AbstractCalcDSLValidator {
}
