/**
 * generated by Xtext
 */
package fr.imta.tp2.tutorial.ui.contentassist;

import fr.imta.tp2.tutorial.ui.contentassist.AbstractMyTutoProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MyTutoProposalProvider extends AbstractMyTutoProposalProvider {
}
