/**
 * generated by Xtext
 */
package fr.imta.tp2.calendarDSL.validation;

import fr.imta.tp2.calendarDSL.validation.AbstractCalendarDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CalendarDSLValidator extends AbstractCalendarDSLValidator {
}
